# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: ABC Install
        # You may pin to the exact commit or the version.
        # uses: lyricwulf/abc@965f6bc43d80ae5289d984f283fbeb91e4c00806
        uses: lyricwulf/abc@v1.2.0
        with:
          # Apt dependencies
          linux: texlive


      - run: |
          mkdir -p `kpsewhich --var-value=TEXMFHOME`
          cd `kpsewhich --var-value=TEXMFHOME`
          wget http://mirror.ctan.org/fonts/emerald.zip
          unzip emerald.zip
          cp -r emerald/. . && rm -rf emerald/
          rm emerald.zip
          updmap --enable Map emerald.map
          texhash
      - name: TeXLive Action
        # You may pin to the exact commit or the version.
        # uses: repaction/texlive@6713a805bd9bab56c4777f06c62b10de1c787750
        uses: repaction/texlive@mini-v2
        with:
          # The LaTeX file to be compiled.
          tex_files: main.tex
          
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.0.0
        with:
          # Artifact name
          name: book.pdf
          # A file, directory or wildcard pattern that describes what to upload
          path: main.pdf
          # The desired behavior if no files are found using the provided path.
     
